LOGIN_URL = "https://judge.beecrowd.com/pt/login"
ACCEPTED_LIST_URL = "https://judge.beecrowd.com/pt/runs?answer_id=1"
HOME_URL = "https://judge.beecrowd.com/pt"
LANGUAGE_ID = {
    "Python 3.11": 44,
    "C": 1,
    "C#": 7,
    "C++": 2,
    "C++17": 16,
    "C++20": 42,
    "C99": 14,
    "Clojure": 26,
    "Dart": 22,
    "Dart 2.17": 39,
    "Dart 3.0": 43,
    "Elixir": 34,
    "Go": 12,
    "Go 1.15": 28,
    "Go 1.20": 46,
    "Haskell": 17,
    "Java": 3,
    "Java 14": 21,
    "Java 19": 40,
    "Java 8": 11,
    "JavaScript": 10,
    "JavaScript 12.18": 30,
    "Julia": 33,
    "Kotlin": 15,
    "Lua": 9,
    "Lua 5.4": 29,
    "OCaml": 18,
    "Pascal": 19,
    "PHP": 24,
    "PHP 8.1": 45,
    "PostgreSQL": 13,
    "Python": 4,
    "Python 3": 5,
    "Python 3.8": 20,
    "Python 3.9": 35,
    "Python 3.9 AI": 36,
    "R": 26,
    "Ruby": 6,
    "Ruby 2.7": 27,
    "Rust": 31,
    "Scala": 8,
    "Swift": 25,
    "Swift 5.8": 47,
    "TypeScript 4.1": 32,
    "TypeScript 5.1": 41,
}

# im too lazy to add all of them please send a pull request if you are reading this
LANGUAGE_EXTENSION = {
    "Python 3.11": ".py",
    "Rust": ".rs",
    "Lua": ".lua",
    "JavaScript": ".js",
    "TypeScript 4.1": ".ts",
    "C99": ".c",
    "C++20": ".cpp",
    "PostgreSQL": ".sql",
    "C#": ".cs",
}

# this too bruhhhhhhhh 😴
LANGUAGE_COMMENT = {
    "Python 3.11": "#",
    "Rust": "//",
    "C99": "//",
    "C++20": "//",
    "C#": "//",
    "PostgreSQL": "--",
    "Lua": "--",
}
UBLOCK_ORIGIN_URL = "https://github.com/gorhill/uBlock/releases/download/1.69.0/uBlock0_1.69.0.firefox.signed.xpi"
